// <auto-generated />
using System;
using EmployeeDirectory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDirectory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDirectory.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Technology",
                            Email = "aditya.wijaya1@company.com",
                            FirstName = "Aditya",
                            HireDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "DevOps Specialist",
                            LastName = "Wijaya",
                            Salary = 8300000m
                        },
                        new
                        {
                            Id = 2,
                            Department = "Technology",
                            Email = "aditya.sari2@company.com",
                            FirstName = "Aditya",
                            HireDate = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Sari",
                            Salary = 9700000m
                        },
                        new
                        {
                            Id = 3,
                            Department = "Human Resources",
                            Email = "mega.hidayat3@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Specialist",
                            LastName = "Hidayat",
                            Salary = 15400000m
                        },
                        new
                        {
                            Id = 4,
                            Department = "Human Resources",
                            Email = "hendra.utomo4@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Specialist",
                            LastName = "Utomo",
                            Salary = 6800000m
                        },
                        new
                        {
                            Id = 5,
                            Department = "Technology",
                            Email = "hendra.utomo5@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "DevOps Specialist",
                            LastName = "Utomo",
                            Salary = 7900000m
                        },
                        new
                        {
                            Id = 6,
                            Department = "Technology",
                            Email = "aditya.sari6@company.com",
                            FirstName = "Aditya",
                            HireDate = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Sari",
                            Salary = 11100000m
                        },
                        new
                        {
                            Id = 7,
                            Department = "Finance",
                            Email = "hendra.santoso7@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Santoso",
                            Salary = 20000000m
                        },
                        new
                        {
                            Id = 8,
                            Department = "Technology",
                            Email = "andi.santoso8@company.com",
                            FirstName = "Andi",
                            HireDate = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Santoso",
                            Salary = 17500000m
                        },
                        new
                        {
                            Id = 9,
                            Department = "Human Resources",
                            Email = "dewi.gunawan9@company.com",
                            FirstName = "Dewi",
                            HireDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Gunawan",
                            Salary = 7800000m
                        },
                        new
                        {
                            Id = 10,
                            Department = "Technology",
                            Email = "rina.sari10@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "QA Engineer",
                            LastName = "Sari",
                            Salary = 19200000m
                        },
                        new
                        {
                            Id = 11,
                            Department = "Human Resources",
                            Email = "dewi.santoso11@company.com",
                            FirstName = "Dewi",
                            HireDate = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Specialist",
                            LastName = "Santoso",
                            Salary = 6300000m
                        },
                        new
                        {
                            Id = 12,
                            Department = "Technology",
                            Email = "siti.sari12@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2023, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Sari",
                            Salary = 13800000m
                        },
                        new
                        {
                            Id = 13,
                            Department = "Operations",
                            Email = "mega.santoso13@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Santoso",
                            Salary = 5000000m
                        },
                        new
                        {
                            Id = 14,
                            Department = "Operations",
                            Email = "rina.santoso14@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Project Manager",
                            LastName = "Santoso",
                            Salary = 14200000m
                        },
                        new
                        {
                            Id = 15,
                            Department = "Human Resources",
                            Email = "rina.santoso15@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2022, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Specialist",
                            LastName = "Santoso",
                            Salary = 13700000m
                        },
                        new
                        {
                            Id = 16,
                            Department = "Human Resources",
                            Email = "mega.kusuma16@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2022, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Kusuma",
                            Salary = 16700000m
                        },
                        new
                        {
                            Id = 17,
                            Department = "Operations",
                            Email = "budi.rahayu17@company.com",
                            FirstName = "Budi",
                            HireDate = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Rahayu",
                            Salary = 19200000m
                        },
                        new
                        {
                            Id = 18,
                            Department = "Human Resources",
                            Email = "siti.kusuma18@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Kusuma",
                            Salary = 7900000m
                        },
                        new
                        {
                            Id = 19,
                            Department = "Finance",
                            Email = "dewi.utomo19@company.com",
                            FirstName = "Dewi",
                            HireDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Utomo",
                            Salary = 20400000m
                        },
                        new
                        {
                            Id = 20,
                            Department = "Finance",
                            Email = "aditya.lestari20@company.com",
                            FirstName = "Aditya",
                            HireDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Lestari",
                            Salary = 18000000m
                        },
                        new
                        {
                            Id = 21,
                            Department = "Technology",
                            Email = "rini.nugroho21@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Nugroho",
                            Salary = 10300000m
                        },
                        new
                        {
                            Id = 22,
                            Department = "Finance",
                            Email = "dewi.utomo22@company.com",
                            FirstName = "Dewi",
                            HireDate = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Accountant",
                            LastName = "Utomo",
                            Salary = 24900000m
                        },
                        new
                        {
                            Id = 23,
                            Department = "Human Resources",
                            Email = "siti.hidayat23@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Hidayat",
                            Salary = 21500000m
                        },
                        new
                        {
                            Id = 24,
                            Department = "Operations",
                            Email = "budi.gunawan24@company.com",
                            FirstName = "Budi",
                            HireDate = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Gunawan",
                            Salary = 23600000m
                        },
                        new
                        {
                            Id = 25,
                            Department = "Marketing",
                            Email = "bambang.utomo25@company.com",
                            FirstName = "Bambang",
                            HireDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Content Writer",
                            LastName = "Utomo",
                            Salary = 8800000m
                        },
                        new
                        {
                            Id = 26,
                            Department = "Human Resources",
                            Email = "andi.santoso26@company.com",
                            FirstName = "Andi",
                            HireDate = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Santoso",
                            Salary = 24800000m
                        },
                        new
                        {
                            Id = 27,
                            Department = "Technology",
                            Email = "andi.rahayu27@company.com",
                            FirstName = "Andi",
                            HireDate = new DateTime(2023, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "QA Engineer",
                            LastName = "Rahayu",
                            Salary = 16200000m
                        },
                        new
                        {
                            Id = 28,
                            Department = "Finance",
                            Email = "aditya.wijaya28@company.com",
                            FirstName = "Aditya",
                            HireDate = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Financial Analyst",
                            LastName = "Wijaya",
                            Salary = 22700000m
                        },
                        new
                        {
                            Id = 29,
                            Department = "Finance",
                            Email = "rini.nugroho29@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2022, 7, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Financial Analyst",
                            LastName = "Nugroho",
                            Salary = 24000000m
                        },
                        new
                        {
                            Id = 30,
                            Department = "Technology",
                            Email = "siti.wijaya30@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2022, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Wijaya",
                            Salary = 23900000m
                        },
                        new
                        {
                            Id = 31,
                            Department = "Finance",
                            Email = "eko.utomo31@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2021, 10, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Accountant",
                            LastName = "Utomo",
                            Salary = 23300000m
                        },
                        new
                        {
                            Id = 32,
                            Department = "Human Resources",
                            Email = "sri.pratama32@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2021, 11, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Pratama",
                            Salary = 17300000m
                        },
                        new
                        {
                            Id = 33,
                            Department = "Human Resources",
                            Email = "hendra.putri33@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2022, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Putri",
                            Salary = 15500000m
                        },
                        new
                        {
                            Id = 34,
                            Department = "Marketing",
                            Email = "dewi.rahayu34@company.com",
                            FirstName = "Dewi",
                            HireDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Marketing Executive",
                            LastName = "Rahayu",
                            Salary = 10500000m
                        },
                        new
                        {
                            Id = 35,
                            Department = "Technology",
                            Email = "hendra.setiawan35@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "QA Engineer",
                            LastName = "Setiawan",
                            Salary = 21100000m
                        },
                        new
                        {
                            Id = 36,
                            Department = "Operations",
                            Email = "fitri.nugroho36@company.com",
                            FirstName = "Fitri",
                            HireDate = new DateTime(2021, 9, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Nugroho",
                            Salary = 22900000m
                        },
                        new
                        {
                            Id = 37,
                            Department = "Human Resources",
                            Email = "andi.utomo37@company.com",
                            FirstName = "Andi",
                            HireDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Utomo",
                            Salary = 15000000m
                        },
                        new
                        {
                            Id = 38,
                            Department = "Human Resources",
                            Email = "siti.gunawan38@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Gunawan",
                            Salary = 19400000m
                        },
                        new
                        {
                            Id = 39,
                            Department = "Finance",
                            Email = "mega.gunawan39@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Accountant",
                            LastName = "Gunawan",
                            Salary = 23700000m
                        },
                        new
                        {
                            Id = 40,
                            Department = "Human Resources",
                            Email = "budi.pratama40@company.com",
                            FirstName = "Budi",
                            HireDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Specialist",
                            LastName = "Pratama",
                            Salary = 10800000m
                        },
                        new
                        {
                            Id = 41,
                            Department = "Human Resources",
                            Email = "sri.sari41@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Sari",
                            Salary = 20300000m
                        },
                        new
                        {
                            Id = 42,
                            Department = "Operations",
                            Email = "agus.hidayat42@company.com",
                            FirstName = "Agus",
                            HireDate = new DateTime(2021, 11, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Hidayat",
                            Salary = 8600000m
                        },
                        new
                        {
                            Id = 43,
                            Department = "Human Resources",
                            Email = "joko.utomo43@company.com",
                            FirstName = "Joko",
                            HireDate = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Utomo",
                            Salary = 6500000m
                        },
                        new
                        {
                            Id = 44,
                            Department = "Operations",
                            Email = "sri.hidayat44@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Project Manager",
                            LastName = "Hidayat",
                            Salary = 22900000m
                        },
                        new
                        {
                            Id = 45,
                            Department = "Technology",
                            Email = "bambang.utomo45@company.com",
                            FirstName = "Bambang",
                            HireDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Utomo",
                            Salary = 13200000m
                        },
                        new
                        {
                            Id = 46,
                            Department = "Human Resources",
                            Email = "rina.nugroho46@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Nugroho",
                            Salary = 20100000m
                        },
                        new
                        {
                            Id = 47,
                            Department = "Technology",
                            Email = "rini.setiawan47@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "DevOps Specialist",
                            LastName = "Setiawan",
                            Salary = 15400000m
                        },
                        new
                        {
                            Id = 48,
                            Department = "Marketing",
                            Email = "rini.pratama48@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Content Writer",
                            LastName = "Pratama",
                            Salary = 17100000m
                        },
                        new
                        {
                            Id = 49,
                            Department = "Technology",
                            Email = "rina.wijaya49@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2021, 9, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Wijaya",
                            Salary = 10800000m
                        },
                        new
                        {
                            Id = 50,
                            Department = "Finance",
                            Email = "rini.santoso50@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Financial Analyst",
                            LastName = "Santoso",
                            Salary = 8100000m
                        },
                        new
                        {
                            Id = 51,
                            Department = "Operations",
                            Email = "rina.wijaya51@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Wijaya",
                            Salary = 18100000m
                        },
                        new
                        {
                            Id = 52,
                            Department = "Operations",
                            Email = "rina.setiawan52@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Setiawan",
                            Salary = 17300000m
                        },
                        new
                        {
                            Id = 53,
                            Department = "Marketing",
                            Email = "eko.pratama53@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Content Writer",
                            LastName = "Pratama",
                            Salary = 15800000m
                        },
                        new
                        {
                            Id = 54,
                            Department = "Operations",
                            Email = "eko.setiawan54@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Project Manager",
                            LastName = "Setiawan",
                            Salary = 9500000m
                        },
                        new
                        {
                            Id = 55,
                            Department = "Marketing",
                            Email = "joko.gunawan55@company.com",
                            FirstName = "Joko",
                            HireDate = new DateTime(2022, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Marketing Executive",
                            LastName = "Gunawan",
                            Salary = 16800000m
                        },
                        new
                        {
                            Id = 56,
                            Department = "Finance",
                            Email = "eko.nugroho56@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Nugroho",
                            Salary = 5800000m
                        },
                        new
                        {
                            Id = 57,
                            Department = "Finance",
                            Email = "eko.pratama57@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2021, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Financial Analyst",
                            LastName = "Pratama",
                            Salary = 5000000m
                        },
                        new
                        {
                            Id = 58,
                            Department = "Finance",
                            Email = "eko.hidayat58@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Hidayat",
                            Salary = 13300000m
                        },
                        new
                        {
                            Id = 59,
                            Department = "Finance",
                            Email = "andi.gunawan59@company.com",
                            FirstName = "Andi",
                            HireDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Gunawan",
                            Salary = 23800000m
                        },
                        new
                        {
                            Id = 60,
                            Department = "Operations",
                            Email = "dewi.nugroho60@company.com",
                            FirstName = "Dewi",
                            HireDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Project Manager",
                            LastName = "Nugroho",
                            Salary = 17800000m
                        },
                        new
                        {
                            Id = 61,
                            Department = "Technology",
                            Email = "mega.hidayat61@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2023, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Hidayat",
                            Salary = 23100000m
                        },
                        new
                        {
                            Id = 62,
                            Department = "Technology",
                            Email = "sri.utomo62@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2024, 8, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "QA Engineer",
                            LastName = "Utomo",
                            Salary = 7600000m
                        },
                        new
                        {
                            Id = 63,
                            Department = "Marketing",
                            Email = "siti.santoso63@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2021, 12, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Marketing Executive",
                            LastName = "Santoso",
                            Salary = 9700000m
                        },
                        new
                        {
                            Id = 64,
                            Department = "Human Resources",
                            Email = "hendra.gunawan64@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2022, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Gunawan",
                            Salary = 7500000m
                        },
                        new
                        {
                            Id = 65,
                            Department = "Technology",
                            Email = "bambang.utomo65@company.com",
                            FirstName = "Bambang",
                            HireDate = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Utomo",
                            Salary = 18000000m
                        },
                        new
                        {
                            Id = 66,
                            Department = "Finance",
                            Email = "mega.gunawan66@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Gunawan",
                            Salary = 23100000m
                        },
                        new
                        {
                            Id = 67,
                            Department = "Finance",
                            Email = "sri.hidayat67@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2022, 5, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Hidayat",
                            Salary = 20900000m
                        },
                        new
                        {
                            Id = 68,
                            Department = "Marketing",
                            Email = "agus.gunawan68@company.com",
                            FirstName = "Agus",
                            HireDate = new DateTime(2021, 11, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Marketing Executive",
                            LastName = "Gunawan",
                            Salary = 21000000m
                        },
                        new
                        {
                            Id = 69,
                            Department = "Marketing",
                            Email = "hendra.pratama69@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "SEO Specialist",
                            LastName = "Pratama",
                            Salary = 21200000m
                        },
                        new
                        {
                            Id = 70,
                            Department = "Technology",
                            Email = "eko.rahayu70@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "QA Engineer",
                            LastName = "Rahayu",
                            Salary = 21400000m
                        },
                        new
                        {
                            Id = 71,
                            Department = "Operations",
                            Email = "joko.rahayu71@company.com",
                            FirstName = "Joko",
                            HireDate = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Rahayu",
                            Salary = 22000000m
                        },
                        new
                        {
                            Id = 72,
                            Department = "Technology",
                            Email = "hendra.kusuma72@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2022, 2, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Kusuma",
                            Salary = 7600000m
                        },
                        new
                        {
                            Id = 73,
                            Department = "Technology",
                            Email = "mega.nugroho73@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "DevOps Specialist",
                            LastName = "Nugroho",
                            Salary = 18200000m
                        },
                        new
                        {
                            Id = 74,
                            Department = "Marketing",
                            Email = "siti.pratama74@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Marketing Executive",
                            LastName = "Pratama",
                            Salary = 8000000m
                        },
                        new
                        {
                            Id = 75,
                            Department = "Operations",
                            Email = "rini.utomo75@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2021, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Project Manager",
                            LastName = "Utomo",
                            Salary = 10500000m
                        },
                        new
                        {
                            Id = 76,
                            Department = "Finance",
                            Email = "mega.setiawan76@company.com",
                            FirstName = "Mega",
                            HireDate = new DateTime(2022, 3, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Accountant",
                            LastName = "Setiawan",
                            Salary = 10600000m
                        },
                        new
                        {
                            Id = 77,
                            Department = "Operations",
                            Email = "sri.rahayu77@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Rahayu",
                            Salary = 9800000m
                        },
                        new
                        {
                            Id = 78,
                            Department = "Technology",
                            Email = "hendra.rahayu78@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Rahayu",
                            Salary = 14100000m
                        },
                        new
                        {
                            Id = 79,
                            Department = "Human Resources",
                            Email = "fitri.rahayu79@company.com",
                            FirstName = "Fitri",
                            HireDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Rahayu",
                            Salary = 7800000m
                        },
                        new
                        {
                            Id = 80,
                            Department = "Marketing",
                            Email = "rina.kusuma80@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Content Writer",
                            LastName = "Kusuma",
                            Salary = 18600000m
                        },
                        new
                        {
                            Id = 81,
                            Department = "Technology",
                            Email = "rini.wijaya81@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Wijaya",
                            Salary = 14900000m
                        },
                        new
                        {
                            Id = 82,
                            Department = "Marketing",
                            Email = "rini.sari82@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Marketing Executive",
                            LastName = "Sari",
                            Salary = 17600000m
                        },
                        new
                        {
                            Id = 83,
                            Department = "Operations",
                            Email = "rini.gunawan83@company.com",
                            FirstName = "Rini",
                            HireDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Operations Staff",
                            LastName = "Gunawan",
                            Salary = 10700000m
                        },
                        new
                        {
                            Id = 84,
                            Department = "Technology",
                            Email = "eko.utomo84@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Utomo",
                            Salary = 23600000m
                        },
                        new
                        {
                            Id = 85,
                            Department = "Finance",
                            Email = "fitri.utomo85@company.com",
                            FirstName = "Fitri",
                            HireDate = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Tax Specialist",
                            LastName = "Utomo",
                            Salary = 13600000m
                        },
                        new
                        {
                            Id = 86,
                            Department = "Human Resources",
                            Email = "siti.sari86@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Sari",
                            Salary = 24000000m
                        },
                        new
                        {
                            Id = 87,
                            Department = "Human Resources",
                            Email = "bambang.putri87@company.com",
                            FirstName = "Bambang",
                            HireDate = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Putri",
                            Salary = 14500000m
                        },
                        new
                        {
                            Id = 88,
                            Department = "Human Resources",
                            Email = "andi.setiawan88@company.com",
                            FirstName = "Andi",
                            HireDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Setiawan",
                            Salary = 15500000m
                        },
                        new
                        {
                            Id = 89,
                            Department = "Technology",
                            Email = "rina.lestari89@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "QA Engineer",
                            LastName = "Lestari",
                            Salary = 5800000m
                        },
                        new
                        {
                            Id = 90,
                            Department = "Human Resources",
                            Email = "andi.pratama90@company.com",
                            FirstName = "Andi",
                            HireDate = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Pratama",
                            Salary = 12300000m
                        },
                        new
                        {
                            Id = 91,
                            Department = "Technology",
                            Email = "budi.kusuma91@company.com",
                            FirstName = "Budi",
                            HireDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Kusuma",
                            Salary = 5800000m
                        },
                        new
                        {
                            Id = 92,
                            Department = "Operations",
                            Email = "joko.setiawan92@company.com",
                            FirstName = "Joko",
                            HireDate = new DateTime(2023, 9, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Project Manager",
                            LastName = "Setiawan",
                            Salary = 5800000m
                        },
                        new
                        {
                            Id = 93,
                            Department = "Technology",
                            Email = "sri.rahayu93@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Rahayu",
                            Salary = 24800000m
                        },
                        new
                        {
                            Id = 94,
                            Department = "Technology",
                            Email = "siti.lestari94@company.com",
                            FirstName = "Siti",
                            HireDate = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Software Engineer",
                            LastName = "Lestari",
                            Salary = 10000000m
                        },
                        new
                        {
                            Id = 95,
                            Department = "Finance",
                            Email = "rina.setiawan95@company.com",
                            FirstName = "Rina",
                            HireDate = new DateTime(2022, 12, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Accountant",
                            LastName = "Setiawan",
                            Salary = 15200000m
                        },
                        new
                        {
                            Id = 96,
                            Department = "Human Resources",
                            Email = "sri.utomo96@company.com",
                            FirstName = "Sri",
                            HireDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Utomo",
                            Salary = 15100000m
                        },
                        new
                        {
                            Id = 97,
                            Department = "Finance",
                            Email = "agus.lestari97@company.com",
                            FirstName = "Agus",
                            HireDate = new DateTime(2022, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Accountant",
                            LastName = "Lestari",
                            Salary = 23100000m
                        },
                        new
                        {
                            Id = 98,
                            Department = "Human Resources",
                            Email = "eko.gunawan98@company.com",
                            FirstName = "Eko",
                            HireDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "Recruiter",
                            LastName = "Gunawan",
                            Salary = 16600000m
                        },
                        new
                        {
                            Id = 99,
                            Department = "Human Resources",
                            Email = "budi.santoso99@company.com",
                            FirstName = "Budi",
                            HireDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "HR Manager",
                            LastName = "Santoso",
                            Salary = 17100000m
                        },
                        new
                        {
                            Id = 100,
                            Department = "Technology",
                            Email = "hendra.rahayu100@company.com",
                            FirstName = "Hendra",
                            HireDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            JobTitle = "UI/UX Designer",
                            LastName = "Rahayu",
                            Salary = 9200000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
